name: CI (Release)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -r win-x64 -c Release --self-contained true .\Bloxstrap\Bloxstrap.csproj

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: FallenStrap (Release) (${{ github.sha }})
        path: .\Bloxstrap\bin\Release\net6.0-windows\win-x64\publish\*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: FallenStrap (Release) (${{ github.sha }})
          path: release

      - name: Rename binary
        run: mv release/FallenStrap.exe FallenStrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: FallenStrap-${{ github.ref_name }}.exe
          name: FallenStrap ${{ github.ref_name }}